improved testing procedure, cleaning up build deps

diff --git a/share/mktests/10-sanity b/share/mktests/10-sanity
--- a/share/mktests/10-sanity
+++ b/share/mktests/10-sanity
@@ -1,13 +1,31 @@
 #!/bin/sh
 
-fail="build environment is grinning and holding a spatula, guess not"
+##
+# Sanity Test
+#   Checks to make sure that we are even able to build something using the
+#   detected compilers
+#.
+
+__sanity_fail="build environment is grinning and holding a spatula, guess not"
 
 echo -n "sanity check... "
 
 echo "int main() { return 0; }" > mktests/tmp.c
-test -f mktests/tmp.c || echo "$fail" || return 1
-$cc mktests/tmp.c -o mktests/tmp.out || (rm mktests/tmp* ; echo "$fail") || return 1
-test -f mktests/tmp.out || (rm mktests/tmp* ; echo "$fail") || return 1
+
+if ! test -f mktests/tmp.c ; then
+	echo "$__sanity_fail"
+	return 1
+fi
+
+if ! $cc mktests/tmp.c -o mktests/tmp.out ; then
+	echo "$__sanity_fail"
+	return 1
+fi
+
+if [ ! -f mktests/tmp.out ] ; then
+	echo "$__sanity_fail"
+	return 1
+fi
 
 rm -f mktests/tmp*
 
