complete overhaul of sources parsing

diff --git a/bmake b/bmake
--- a/bmake
+++ b/bmake
@@ -44,6 +44,8 @@ EOF
 #   long equivalent, then a variable with that single character is created.
 #   All non-option parameters are skipped (anything that does not begin with a
 #   dash).
+# Version
+#   1.0
 # Parameters
 #   string shortopts
 #     A list of short options that are accepted. Options followed by a colon
@@ -176,6 +178,16 @@ getopt_long()
 	return 0
 }
 
+##
+# copyfile Function
+#   Copies the given file, adding the md5sum for future checking.
+# Parameters
+#   string path
+#     The output file path.
+#   optional integer mode
+#     Modifies the file mode through the chmod command.
+#.
+
 copyfile()
 {
 	echo "# Generated by BetterMake" > "$1"
@@ -185,6 +197,40 @@ copyfile()
 
 	test ! -z "$2" && chmod "$2" "$1"
 }
+
+##
+# chkfile Function
+#   Checks a file to verify that it has not been changed since the last bmake
+#   install or update by verifying the MD5 checksum.
+# Parameters
+#   string path
+#     The path to the file to be checked.
+# Return Value
+#   Returns '0' if the checksums match, non-zero if they do not match.
+#.
+
+chkfile()
+{
+	orig="`cat "$1" | sed -n '2p' | sed -n 's/^.*md5sum: \([0-9a-fA-F]*\).*$/\1/p'`"
+	chk="`cat "$1" | sed -n '4,$p' | md5sum | head -c32`"
+
+	if [ "$orig" = "$chk" ] ; then
+		return 0
+	else
+		return 1
+	fi
+}
+
+##
+# quotify Function
+#   Takes an input string and escapes all double quotes so that the output
+#   string is useable inside double-quotes.
+# Version
+#   1.0
+# Parameters
+#   string input
+#     The input text.
+#.
 
 quotify()
 {
@@ -322,15 +368,32 @@ testcmd()
 	esac
 }
 
-if [ "$#" -eq 0 ] ; then
-	usage
-	exit
-fi
+##
+# cmd_install Function
+#   Processes an install command, copying the files into the target directory.
+#   A force install will automatically overwrite any current files.
+# Parameters
+#   string params
+#     The set of parameters to the command, generally '"$@"'.
+#.
 
-cmd=$1 ; shift
+cmd_install()
+{
+	help="" ; force=""
+	eval `getopt_long f? f,force ?,help -- "$@"`
+	if [ -n "$err" ] ; then echo "$err" ; exit 1 ; fi
 
-case "$cmd" in
-	install)
+	if [ "$help" ] ; then
+		cat <<USAGE
+usage: bmake install [-f | --force]
+Options
+  -f, --force   Forces all files to be installed overwriting existing files
+      --help    Produce this help message
+USAGE
+		exit 0
+	fi
+
+	if [ -z "$force" ] ; then 
 		for file in "Makefile.in" "configure"
 		do
 			test -e "$file" || continue
@@ -338,27 +401,74 @@ case "$cmd" in
 			echo "$file already exists, cowardly giving up" >&2
 			exit 1
 		done
+	fi
 
-		copyfile "Makefile.in"
-		copyfile "configure" 0755
-		test ! -d mktests && mkdir mktests
-		for file in "mktests/00-cc" "mktests/00-ld"
+	copyfile "Makefile.in"
+	copyfile "configure" 0755
+	test ! -d mktests && mkdir mktests
+}
+
+##
+# cmd_update Function
+#   Updates the currently existing build files, replacing old files with the
+#   new versions. Without the '--force' option, if any of the previous files
+#   were modified, then the update will abort and an error will be reported.
+# Parameters
+#   string params
+#     The set of parameters to the command, generally '"$@"'.
+#.
+
+cmd_update()
+{
+	help="" ; force=""
+	eval `getopt_long f? f,force ?,help -- "$@"`
+	if [ -n "$err" ] ; then echo "$err" ; exit 1 ; fi
+
+	if [ "$help" ] ; then
+		cat <<USAGE
+usage: bmake update [-f | --force]
+Options
+  -f, --force   Forces all files to be updated, overwriting existing files
+      --help    Produce this help message
+USAGE
+		exit 0
+	fi
+
+	if [ -z "$force" ] ; then 
+		fail=""
+		for file in "Makefile.in" "configure" "mktests/*"
 		do
-			copyfile "$file" 0755
+			test -f "$file" || continue
+			chkfile "$file" && continue
+
+			echo "error: $file has been modified since the last install or update" >&2
+			fail=1
 		done
 
-		;;
+		test "$fail" && exit 1
+	fi
 
-	update)
-		copyfile "Makefile.in"
-		copyfile "configure" 0755
-		test ! -d mktests && mkdir mktests
-		for file in "mktests/00-cc" "mktests/00-ld"
-		do
-			copyfile "$file" 0755
-		done
+	copyfile "Makefile.in"
+	copyfile "configure" 0755
+	test ! -d mktests && mkdir mktests
+	for file in "mktests/*"
+	do
+		test -f "$file" || continue
+		copyfile "$file" 0755
+	done
+}
 
-		;;
+# Verify we have a command
+if [ "$#" -eq 0 ] ; then
+	usage
+	exit
+fi
+
+# Process the current command, passing to the proper handler
+cmd=$1 ; shift
+case "$cmd" in
+	install) cmd_install "$@" ;;
+	update) cmd_update "$@" ;;
 	
 	target | test )
 		"${cmd}cmd" "$@" ;;
