properly updates files, added more flags

diff --git a/bmake b/bmake
--- a/bmake
+++ b/bmake
@@ -3,6 +3,25 @@
 sharedir="`dirname $0`/share"
 
 ##
+# contains Function
+#   Determine if a string contains a substring.
+# Version
+#   1.0
+# Parameters
+#   string str
+#     The base string to check if it contains the substring.
+#   string sub
+#     The substring searched for in 'str'.
+# Return Value
+#   Returns success if found, failure otherwise.
+#.
+
+contains()
+{
+	test "$1" != "${1#*"$2"}"
+}
+
+##
 # usage Function
 #   Displays the usage information regarding the list of possible commands.
 # Parameters
@@ -20,7 +39,7 @@ usage()
 	fi
 
 	cat <<EOF >&$fd
-bmake command [options]
+`basename "$0"` <command> [options]
 
 Possible commands are:
   install
@@ -44,6 +63,8 @@ EOF
 #   long equivalent, then a variable with that single character is created.
 #   All non-option parameters are skipped (anything that does not begin with a
 #   dash).
+# Version
+#   1.0
 # Parameters
 #   string shortopts
 #     A list of short options that are accepted. Options followed by a colon
@@ -55,8 +76,8 @@ EOF
 #   -- args ...
 #     After the string '--', all of the parameters are placed after it.
 #     Generally the value '"$@"' should be passed.
-# Return Value
-#   The returned text should be dirctly evaluated using the 'eval' build-in
+# Printed
+#   The returned text should be dirctly evaluated using the 'eval' built-in
 #   function. All the parameters will be stored in their respective variables.
 #   If an error occurs during processing, then the value 'err' will be set to
 #   a text error message.
@@ -117,13 +138,13 @@ getopt_long()
 			;;
 
 		-*)
-			arg=`echo $arg | tail -c+2`
+			arg="${arg#-}"
 			local needval=""
 			while [ -n "$arg" ]
 			do
 				short=`echo $arg | head -c1`
 
-				if ! echo "$opt" | grep "$short" >/dev/null 2>/dev/null ; then
+				if ! contains "$opt" "$short" ; then
 					echo "err=\"invalid parameter '-$short'\";"
 					return 1
 				fi
@@ -131,7 +152,7 @@ getopt_long()
 				long=`echo "$param" | sed -n "s/.* $short,\\([^ ]*\\) .*/\1/p"`
 				arg=`echo $arg | tail -c+2`
 
-				if ! echo "$opt" | grep "$short:" >/dev/null 2>/dev/null ; then
+				if ! contains "$opt" "$short:" ; then
 					if [ -z "$long" ] ; then
 						echo -n "$short=1;"
 					else
@@ -177,6 +198,24 @@ getopt_long()
 }
 
 ##
+# isscript Function
+#   Test if the input file is a script, checking for a shebang.
+# Version
+#   1.0
+# Parameters
+#   string path
+#     FIle path to test if it is a script.
+# Return Value
+#   Returns zero if it is a script, non-zero otherwise.
+#.
+
+isscript()
+{
+	read line < "$1"
+	test -z "${line##"#!"*}"
+}
+
+##
 # copyfile Function
 #   Copy the file from the share directoy to the target output. The file is
 #   prefixed with its MD5 checksum for consistency.
@@ -191,12 +230,58 @@ getopt_long()
 
 copyfile()
 {
-	echo "# Generated by BetterMake" > "$1"
+	local src="$sharedir/$1"
+
+	rm -f "$1"
+
+	if isscript "$src" ; then head -n 1 "$src" >> "$1" ; fi
+
+	echo "# Generated by BetterMake" >> "$1"
 	echo "# md5sum: "`md5sum "$sharedir/$1" | head -c32` >> "$1"
-	echo >> "$1"
-	cat "$sharedir/$1" >> "$1"
+
+	if isscript "$src" ; then
+		tail -n +2 "$src" >> "$1"
+	else
+		echo >> "$1"
+		cat "$sharedir/$1" >> "$1"
+	fi
 
 	test ! -z "$2" && chmod "$2" "$1"
+}
+
+##
+# checkfile Function
+#   Check the file, determining if the MD5 checksum matches.
+# Version
+#   1.0
+# Parameters
+#   string filename
+#     Source and target file name.
+#   octal mode
+#     Target file mode
+# Return Value
+#   True if they mach, false otherwise.
+#.
+
+checkfile()
+{
+	local md5=""
+	local chk=""
+	local dest="$1"
+
+	while read line
+	do
+		md5="${line##"# md5sum: "}"
+		test "$md5" != "$line" && break
+	done < "$dest"
+
+	if isscript "$dest" ; then
+		chk="`sed '2,3d' "$dest" | md5sum | head -c32`"
+	else
+		chk="`sed '1,3d' "$dest" | md5sum | head -c32`"
+	fi
+
+	test "$md5" = "$chk"
 }
 
 quotify()
@@ -238,6 +323,48 @@ quote()
 
 	printf "'%s'" "$str"
 }
+
+##
+# dblescape Function
+#   Given an input string, it escapes all double quotes and escape characters.
+# Version
+#   1.0
+# Parameters
+#   string input
+#     The input text.
+# Printed
+#   Prints out the escaped string.
+#.
+
+dblescape()
+{
+	local str="$*"
+
+	while [ 1 ]
+	do
+		local piece="${str%%[\\\"]*}"
+		test "$piece" = "$str" && break
+		local chr="${str#"$piece"}"
+		str="${str#*[\\\"]}"
+		printf %s%s "$piece" "\\${chr%"$str"}"
+	done
+
+	printf %s "$str"
+}
+
+##
+# dblquote Function
+#   Given an input string, it escapes all double quotes and escape characters.
+#   Do note that this function does not surround the resulting string with
+#   quotes.
+# Version
+#   1.0
+# Parameters
+#   string input
+#     The input text.
+# Printed
+#   Prints out the quoted string.
+#.
 
 dblquote()
 {
@@ -292,7 +419,7 @@ targetcmd()
 			do
 				test -z "${arg%%-*}" && continue
 
-				printf "Target\n\tOutput\t\"%s\"\nEndTarget\n" `dblquote "$arg"` >> "$srcfile"
+				printf "Target\n\tOutput\t\"%s\"\nEndTarget\n" `dblescape "$arg"` >> "$srcfile"
 			done
 
 			;;
@@ -335,15 +462,64 @@ testcmd()
 	esac
 }
 
-if [ "$#" -eq 0 ] ; then
-	usage
-	exit
-fi
+##
+# cmd Function
+#   Process any passed commands.
+#.
 
-cmd=$1 ; shift
+cmd()
+{
+	if [ "$#" -eq 0 ] ; then
+		usage
+		exit
+	fi
 
-case "$cmd" in
-	install)
+	cmd=$1 ; shift
+
+	case "$cmd" in
+		install | update ) "cmd_$cmd" "$@" ;;
+		
+		target | test )
+			"${cmd}cmd" "$@" ;;
+		
+		help | -? | --help)
+			usage
+			;;
+
+		*)
+			echo "Unknown command '$cmd'" >&2
+			echo >&2
+			usage 2
+			exit 1
+			;;
+	esac
+}
+
+##
+# cmd_install Function
+#   Process the install command.
+#.
+
+cmd_install()
+{
+	eval `getopt_long bf? b,bare f,force ?,help -- "$@"`
+
+	if [ "$err" ] || [ "$help" ] ; then
+		test "$err" && fd=2 || fd=1
+		cat <<EOF >&$fd
+bmake install [options]
+
+Install a BetterMake environment to the current directory.
+
+Possible options are:
+  -?,--help   Display this information
+  -b,--bare   Produce a bare BetterMake environment, installing no tests
+  -f,--force  Force a new installation even if a previous install is detcted
+EOF
+		return
+	fi
+
+	if [ -z "$force" ] ; then
 		for file in "Makefile.in" "configure"
 		do
 			test -e "$file" || continue
@@ -351,37 +527,75 @@ case "$cmd" in
 			echo "$file already exists, cowardly giving up" >&2
 			exit 1
 		done
+	fi
 
-		copyfile "Makefile.in"
-		copyfile "configure" 0755
-		test ! -d mktests && mkdir mktests
+	copyfile "Makefile.in"
+	copyfile "configure" 0755
+	test ! -d mktests && mkdir mktests
+
+	if [ -z "$bare" ] ; then
 		for file in "mktests/00-cc" "mktests/00-ld"
 		do
 			copyfile "$file" 0755
 		done
+	fi
+}
 
-		;;
+##
+# cmd_update Function
+#   Process the update command.
+#.
 
-	update)
-		copyfile "Makefile.in"
-		copyfile "configure" 0755
-		test ! -d mktests && mkdir mktests
-		for file in "mktests/00-cc" "mktests/00-ld"
+cmd_update()
+{
+	eval `getopt_long f? f,force v,verbose ?,help -- "$@"`
+
+	if [ "$err" ] || [ "$help" ] ; then
+		test "$err" && fd=2 || fd=1
+		cat <<EOF >&$fd
+bmake update [options]
+
+Update the BetterMake environment, copying any updated build files and tests
+to the current project. Note that any modified files will be flagged to
+prevent ovewriting user modifications.
+
+Possible options are:
+  -?,--help     Display this information
+  -f,--force    Force the update even if file have been modified
+  -v,--verbose  Print verbose information.
+EOF
+		return
+	fi
+
+	if [ -z "$force" ] ; then
+		for file in configure Makefile.in mktests/[0-9][0-9]-*
 		do
-			copyfile "$file" 0755
+			test -f "$file" || break
+
+			if ! checkfile "$file" ; then
+				echo "'$file' has been modified, giving up on update" >&2
+				exit 1
+			fi
+			test "$verbose" && echo "~ ok file '$file'"
 		done
+	fi
 
-		;;
-	
-	target | test )
-		"${cmd}cmd" "$@" ;;
-	
-	help | -? | --help)
-		usage
-		;;
+	copyfile "configure" 0755
+	test "$verbose" && echo "~ copied file 'configure'"
+	copyfile "Makefile.in"
+	test "$verbose" && echo "~ copied file 'Makefile.in'"
 
-	*)
-		usage 2
-		exit 1
-		;;
-esac
+	test ! -d mktests && mkdir mktests
+	for file in mktests/[0-9][0-9]-*
+	do
+		test -f "$file" || break
+
+		copyfile "$file" 0755
+		test "$verbose" && echo "~ copied file '$file'"
+	done
+}
+
+
+# pass control to the command processor
+
+cmd "$@"
diff --git a/share/mktests/00-cc b/share/mktests/00-cc
--- a/share/mktests/00-cc
+++ b/share/mktests/00-cc
@@ -13,20 +13,24 @@
 #     Adds flags for dependency tracking.
 #.
 
-echo -n "checking for compiler (${toolchain}gcc)... "
-if which "${toolchain}gcc" >/dev/null ; then
-	echo yes ; cc="${toolchain}gcc"
-else
-	echo no
+test "$cc" && echo "compiler specified ($cc)"
 
-	echo -n "checking for compiler (${toolchain}cc)... "
-	if which "${toolchain}gcc" >/dev/null ; then
-		echo yes ; cc="${toolchain}cc"
-	else
-		echo "error: no compiler found"
-		exit 1
-	fi
+if [ -z "$cc" ] && [ "$CC" ] ; then
+	echo -n "checking for compiler (${toolchain}$CC)... "
+	which "${toolchain}$CC" > /dev/null && { echo yes ; cc="${toolchain}$CC" ; } || echo no
 fi
+
+if [ -z "$cc" ] ; then
+	echo -n "checking for compiler (${toolchain}gcc)... "
+	which "${toolchain}gcc" > /dev/null && { echo yes ; cc="${toolchain}gcc" ; } || echo no
+fi
+
+if [ -z "$cc" ] ; then
+	echo -n "checking for compiler (${toolchain}cc)... "
+	which "${toolchain}cc" > /dev/null && { echo yes ; cc="${toolchain}cc" ; } || echo no
+fi
+
+test -z "$cc" && { echo "error: no compiler found" ; exit 1 ; }
 
 precc="$precc if [ ! -d \"\$(@D)/$depdir\" ] ; then mkdir \"\$(@D)/$depdir\" ; fi ; "
 CFLAGS="$CFLAGS -MD -MP -MF \$(@D)/$depdir/\$(@F).dep"
diff --git a/share/mktests/00-ld b/share/mktests/00-ld
--- a/share/mktests/00-ld
+++ b/share/mktests/00-ld
@@ -8,17 +8,21 @@
 #     Set to the available linker.
 #.
 
-echo -n "checking for linker (${toolchain}gcc)... "
-if which "${toolchain}gcc" >/dev/null ; then
-	echo yes ; ld="${toolchain}gcc"
-else
-	echo no
+test "$ld" && echo "linker specified ($ld)"
 
-	echo -n "checking for linker (${toolchain}ld)... "
-	if which "${toolchain}gcc" >/dev/null ; then
-		echo yes ; ld="${toolchain}ld"
-	else
-		echo "error: no linker found"
-		exit 1
-	fi
+if [ -z "$ld" ] && [ "$LD" ] ; then
+	echo -n "checking for linker (${toolchain}$LD)... "
+	which "${toolchain}$LD" > /dev/null && { echo yes ; ld="${toolchain}$LD" ; } || echo no
 fi
+
+if [ -z "$ld" ] ; then
+	echo -n "checking for linker (${toolchain}gcc)... "
+	which "${toolchain}gcc" > /dev/null && { echo yes ; ld="${toolchain}gcc" ; } || echo no
+fi
+
+if [ -z "$ld" ] ; then
+	echo -n "checking for linker (${toolchain}ld)... "
+	which "${toolchain}ld" > /dev/null && { echo yes ; ld="${toolchain}ld" ; } || echo no
+fi
+
+test -z "$ld" && { echo "error: no linker found" ; exit 1 ; }
diff --git a/share/mktests/10-sanity b/share/mktests/10-sanity
--- a/share/mktests/10-sanity
+++ b/share/mktests/10-sanity
@@ -17,14 +17,16 @@ if ! test -f mktests/tmp.c ; then
 	return 1
 fi
 
-if ! $cc mktests/tmp.c -o mktests/tmp.out ; then
-	echo "$__sanity_fail"
-	return 1
-fi
+if [ "%cc" ] ; then
+	if ! $cc mktests/tmp.c -o mktests/tmp.out ; then
+		echo "$__sanity_fail"
+		return 1
+	fi
 
-if [ ! -f mktests/tmp.out ] ; then
-	echo "$__sanity_fail"
-	return 1
+	if [ ! -f mktests/tmp.out ] ; then
+		echo "$__sanity_fail"
+		return 1
+	fi
 fi
 
 rm -f mktests/tmp*
