improved code for checks

diff --git a/share/configure b/share/configure
--- a/share/configure
+++ b/share/configure
@@ -80,6 +80,16 @@ process_sources()
 				local ldextra=''
 				;;
 
+			"TestApplication")
+				printf 'bmake_test: %s_test\n\n' "$target" >> "$2"
+				printf '%s_test: %s\n' "$target" "$target" >> "$2"
+				printf '\t@./%s || echo "**** %s failed ****"\n\n' "$target" "$target" >> "$2"
+				printf '%s: %s | all\n' "$target" "$obj" >> "$2"
+				printf '\t%s\n\n' "`printf '$(LD)%s %s -o $@ $(LDFLAGS)\n' "$ldflags" "$obj"`" >> "$2"
+				local clean="`printf '\trm -f %s' "$target"`"
+				local ldextra=''
+				;;
+
 			"Library")
 				printf 'bmake_all: lib%s.a lib%s.so.%s\n\n' "$target" "$target" "$version" >> "$2"
 				printf 'lib%s.a: %s\n\t%s\n\n' "$target" "$obj" "`printf 'ar rcs $@ $^'`" >> "$2"
