bug fixes, added local builds

diff --git a/share/configure b/share/configure
--- a/share/configure
+++ b/share/configure
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 ##
 # extract Function
@@ -17,7 +17,7 @@ extract()
 }
 
 ##
-# process_soucres Function
+# process_sources Function
 #   Inputs the sources configuration file and produces the corresponding
 #   makefile.
 # Parameters
@@ -38,8 +38,9 @@ process_sources()
 		local copy="`printf %s "$remaining" | sed '/^\s*EndTarget\s*$/,$d'`"
 		test "$copy" = "$remaining" && break
 
-		local target="`extract "$copy" Output`"
+		local target="`extract "$copy" Name`"
 		local type="`extract "$copy" Type`"
+		local local="`extract "$copy" Local`"
 		local version="`extract "$copy" Version`"
 		local sources="`extract "$copy" Source`"
 		local obj="`printf %s "$sources" | sed 's/.c\(pp\)\?$/.o/'`"
@@ -48,20 +49,36 @@ process_sources()
 		test -z "$version" && version="0.0.0"
 		local shortversion="${version%%.*}"
 
+		case "$local" in
+			[Tt][Rr][Uu][Ee] | [Yy][Ee][Ss] )
+				local cflags=" -I\"$HOME/include\""
+				local ldflags=" -L\"$HOME/lib\" -Wl,-rpath=\"$HOME/lib\""
+				;;
+
+			[Ff][Aa][Ll][Ss][Ee] | [Nn][Oo] | "")
+				local cflags=""
+				local ldflags=""
+				;;
+
+			*)
+				echo "invalid local value \"$local\"" >&2
+				exit 1
+		esac
+
 		case "$type" in
 			"Application" | "" )
 				printf 'bmake_all: %s\n\n' "$target" >> "$2"
-				printf '%s: %s\n\t%s\n\n' "$target" "$obj" "`printf '$(LD) $^ -o $@ $(LDFLAGS)\n'`" >> "$2"
+				printf '%s: %s\n\t%s\n\n' "$target" "$obj" "`printf '$(LD)%s $^ -o $@ $(LDFLAGS)\n' "$ldflags"`" >> "$2"
 				local clean="`printf '\trm -f %s' "$target"`"
 				local ldextra=''
 				;;
 
 			"Library")
-				printf 'bmake_all: lib%s.a lib%s.%s\n\n' "$target" "$target" "$version" >> "$2"
+				printf 'bmake_all: lib%s.a lib%s.%s.so\n\n' "$target" "$target" "$version" >> "$2"
 				printf 'lib%s.a: %s\n\t%s\n\n' "$target" "$obj" "`printf 'ar rcs $@ $^'`" >> "$2"
-				printf 'lib%s.%s: %s\n\t%s\n\n' "$target" "$version" "$obj" \
-					"`printf '$(CC) -fpic -shared -Wl,-soname,lib%s.so.%s -o $@ $^' "$target" "$shortversion"`" >> "$2"
-				local clean="`printf '\trm -f lib%s.a lib%s.%s' "$target" "$target" "$version"`"
+				printf 'lib%s.%s.so: %s\n\t%s\n\n' "$target" "$version" "$obj" \
+					"`printf '$(CC)%s -fpic -shared -Wl,-soname,lib%s.so.%s -o $@ $^' "$ldflags" "$target" "$shortversion"`" >> "$2"
+				local clean="`printf '\trm -f lib%s.a lib%s.%s.so' "$target" "$target" "$version"`"
 				local ldextra=' -fpic'
 				;;
 
@@ -71,7 +88,7 @@ process_sources()
 
 		for file in $sources
 		do
-			printf '%s: %s\n\t$(bmake_PRECC)\n\t$(CC) -c $< -o $@ $(CFLAGS)%s\n\n' "`printf %s "$file" | sed 's/.c\(pp\)\?$/.o/'`" "$file" "$ldextra" >> "$2"
+			printf '%s: %s\n\t$(bmake_PRECC)\n\t$(CC)%s -c $< -o $@ $(CFLAGS)%s\n\n' "`printf %s "$file" | sed 's/.c\(pp\)\?$/.o/'`" "$file" "$cflags" "$ldextra" >> "$2"
 		done
 
 		printf 'bmake_clean: %s_clean\n\n' "$target" >> "$2"
